### ISSUE TITLE
Installing on macOS Sierra 10.12.6 does not work

### ISSUE THREAD

**Issue by NilsKalbfuss** [qinzhu/VisCello.celegans#1]
I tried to install VisCello.celegans, but fail at the very last step.
When I type in the devtools::install_local("VisCello.celegans") command, I am always asked to update some packages (see below):
<img width="596" alt="Screen Shot 2019-10-16 at 12 48 25" src="https://user-images.githubusercontent.com/52318978/66912821-9e285900-f013-11e9-9cf5-12a607292da5.png">
I tried all different options but I always end up with the following error message: 
<img width="592" alt="Screen Shot 2019-10-16 at 12 48 57" src="https://user-images.githubusercontent.com/52318978/66912966-f65f5b00-f013-11e9-93b7-a351205ef353.png">

If I do not update anything, I end up with the following error message:

<img width="619" alt="Screen Shot 2019-10-16 at 12 54 48" src="https://user-images.githubusercontent.com/52318978/66913114-4a6a3f80-f014-11e9-90ab-0179ffa23755.png">

I hope you have some idea what could help.

Best,
Nils

**Comment by qinzhu** [comment]
Hi Nils, 
Can you try this top answer: https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c?

**Comment by NilsKalbfuss** [comment]
Hi Qin,
Thanks a lot!!! It works! I am super happy!

Best,
Nils
On 16 Oct 2019, at 18:49, Qin Zhu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Nils,
Can you try this top answer: https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c?
