### ISSUE TITLE
Recent failure in cello()

### ISSUE THREAD

**Issue by sarina-kopf** [qinzhu/VisCello.celegans#2]
I am using a Mac OS Sierra Version 10.12.6, running "R version 3.6.3 (2020-02-29)". I have been hosting VisCello in R to do some data analysis for some time. All of the sudden, it failed yielding the following error:

Listening on http://127.0.0.1:4816
Warning: Error in module: unused arguments (showcols_basic = ctype_cols_basic, showcols_advanced = ctype_cols_advanced, tabset = "ct")
  53: force
  52: domain$wrapSync
  51: promises::with_promise_domain
  50: withReactiveDomain
  49: callModule
  48: server [/Library/Frameworks/R.framework/Versions/3.6/Resources/library/VisCello.celegans/app/server.R#95]
Error in module(childScope$input, childScope$output, childScope, ...) : 
  unused arguments (showcols_basic = ctype_cols_basic, showcols_advanced = ctype_cols_advanced, tabset = "ct")

**Comment by qinzhu** [comment]
Can you provide some details? Does it crash when launch or when doing a specific operation? Are you using VisCello.celegans or VisCello? Did you recently update R or VisCello before the crash happens?

**Comment by sarina-kopf** [comment]
I am using VisCello.celegans, it crashes upon launch, and I have updated neither R nor my Computer.
________________________________

**Comment by qinzhu** [comment]
Not sure what happened. I tested using a clean macOS system and it is working. Can you try re-install the package and update all dependent packages?
