### ISSUE TITLE
Issue launching VisCello with local Shiny server

### ISSUE THREAD

**Issue by shahlab-ucla** [qinzhu/VisCello.celegans#4]
Hi, I was able to get VisCello working locally and installed a Shiny server. The server works and launches the example apps. Adding VisCello to the server gives the following error in the logs:

Error in as_tibble(readRDS("data/lineage_tree_tbl.rds")) "
    could not find function "as_tibble"
Calls: runApp ... force -> sourceUTF8 -> eval -> eval -> ..stacktraceon..
Execution halted

Any help getting us up and running would be greatly appreciated. I tried doing this by copying the VisCello installation directory to the example app directory.

**Comment by qinzhu** [comment]
Directly copying VisCello to server does not install the dependent packages. So you need to make sure all dependencies are installed in the server-end R. You can try running the VisCello installation code on the server R.
