### ISSUE TITLE
`git lfs clone` is deprecated.

### ISSUE THREAD

**Issue by stankerstjens** [qinzhu/VisCello.celegans#5]
When cloning the repository using the instructions in the README the following warning is given (git version 2.29.2):

```console
$ git lfs clone https://github.com/qinzhu/VisCello.celegans.git
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
```

This may deserve a comment in your installation guide.

**Comment by knagakura** [comment]
Hi, I'm not developer of this app, 
but I think it is 
not  "git lfs clone", 
but "git-lfs clone", isn't it?

**Comment by qinzhu** [comment]
Thanks for the suggestions and comments and sorry for late reply!
The warning message can be ignored. I've also updated the installation guide to provide related information.
